### PR TITLE
[Bugfix] Mean Reciprocal Rank

### PR DESCRIPTION
**Pull request by yifeim**
MRR should only consider the first element in the return list.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by yifeim** [comment]
@muralibalki could you review? Thanks.

**Comment by yifeim** [comment]
@chrisking Just realized that this is still open; could you please take a look?

Thanks,
Yifei

**Comment by chrisking** [comment]
Looks good other than the large volume of STD_output. Can you clean that up and we should be good to go.

**Comment by yifeim** [comment]
Do you mean the results from ipynb? The notebooks were updated to reflect the changes in the metrics. If we clear out the results, we may not know if the notebooks would run correctly at a later time.

**Comment by chrisking** [comment]
Generally we pull those due to confusing users when they first open the notebook ... It is a form of functional test though...

**Pull request merged**
